### ISSUE TITLE
Scroll one cell at a time

### ISSUE THREAD

**Issue by abcworlddev** [Akkyie/AKPickerView#50]
Hello, 
Thanks for your great library!

I would like for it to sort of scroll/snap one cell at a time when scrolling side to side.
When I scroll, the position is after 2 or 3 or more items. I want property like pageenabled so would like it to work like apple camera. (Apple camera move only one cell at a time)

When I tried with pageenable property and targetContentOffsetForProposedContentOffset:withScrollingVelocity of UICollectionViewFlowLayout, I have lots of problems. Can you make more enhancement for me?

Thanks for your great library again!
Thanks,

Loannis

**Comment by Akkyie** [comment]
Thank you for using my control!

I think the behavior of the picker view on Apple's Camera is different to 'paging', because it doesn't allows user to direct touch. But it exists as merely an indicator shows which the current camera mode is, and switching pages is done by other way.
You may mimic the Camera's UI by putting `UILongPressGestureRecognizer`, and when it fires, manually move the picker view by `selectItem:animated:`.

I think it is more like Camera's UI, than implementing paging on picker view. So this time I'm not planning to implement paging. But any additional proposals or requests are welcomed.

**Comment by abcworlddev** [comment]
Thanks for your help!

**Comment by Akkyie** [comment]
Welcome. Thank you for using my control again!
